services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - DB_CONNECTION=sqlserver://sa:Expecto89$@host.docker.internal:1433?database=ResidenciasDB
    networks:
      - app-network

networks:
  app-network:
    driver: bridge